remote_theme: jekyll-material-theme/jekyll-material-theme
plugins:
- jekyll-remote-theme
show_downloads: false
title: PassWorst
name: fr000gs
email: f47fr0g@gmail.com
description: Passworst: the Worst Password Manager

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "pages"
      toc: true
      
